### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by KMing-L** [Btlmd/sast2022-crawler-SQL-training#16]
https://git.tsinghua.edu.cn/lkm20/3.0-hw2/-/tree/master

**Comment by Btlmd** [comment]
- 知乎爬虫

  - Cookie 是否保证已经失效？否则有账号风险
  - 实现合理

- WebVPN

  - 学期等信息不应直接硬编码到代码中，而更应考虑从页面中获得，如

    ```python
    credit = {'2020-秋': 0, '2021-春': 0, '2021-秋': 0, '2022-春': 0}
    grade_point = {'2020-秋': 0, '2021-春': 0, '2021-秋': 0, '2022-春': 0}
    ```

    导致的运行结果就会是

    ```
    Traceback (most recent call last):
      File "webvpn.py", line 192, in <module>
        credit, grade_point = web.get_grades()
      File "webvpn.py", line 169, in get_grades
        credit[eles[5].string.strip()] += int(eles[2].string.strip())
    KeyError: '2021-夏'
    ```

    因为似乎没有考虑夏季学期 \doge

- SQL
  - 查询正确

- 代码风格
  - README 清晰易懂
