### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by whimmmmm** [Btlmd/sast2022-crawler-SQL-training#17]
https://git.tsinghua.edu.cn/luoyq21/crawler_hw2
2021010723

**Comment by Btlmd** [comment]
- 知乎爬虫

  - Cookie 是否已经失效？否则有账号风险

  - 实现合理

  - `get_question `中是否有调试代码没有删除，如

    ```python
    def get_question(self, qid: int) -> dict:
        qid = 543619883
    ```

  - 提交的导出 SQL 文件中没有包括 `record` 表？

- WebVPN

  - 可能是某些环境差异，在我这里您的代码无法正常运行

    ```python
    Traceback (most recent call last):
      File "webvpn.py", line 200, in <module>
        webvpn.get_grades()
      File "webvpn.py", line 152, in get_grades
        if feature[5].text.strip() == courses[-1].find_all('td')[5].text.strip():
    IndexError: list index out of range
    ```
  - 可能是使用了一些不够鲁棒的索引方式 (?)

- SQL
  - 查询正确

- 代码风格

  - 是否考虑使用些中间变量，如

    ```python
    created = int(json1['initialState']['entities']['questions'][str(qid)]['created'])
    followerCount = int(json1['initialState']['entities']['questions'][str(qid)]['followerCount'])
    visitCount = int(json1['initialState']['entities']['questions'][str(qid)]['visitCount'])
    answerCount = int(json1['initialState']['entities']['questions'][str(qid)]['answerCount'])
    title = json1['initialState']['entities']['questions'][str(qid)]['title']
    tmp = BS(json1['initialState']['entities']['questions'][str(qid)]['detail'],'html.parser')
    ```

    考虑使用

    ```python
    info = json1['initialState']['entities']['questions'][str(qid)]
    ```

    避免重复
