### ISSUE TITLE
Homework Submit 

### ISSUE THREAD

**Issue by zerolllin** [Btlmd/sast2022-crawler-SQL-training#6]
https://git.tsinghua.edu.cn/zhangyik21/crawler_sql_excersice.git  2021010793

**Comment by Btlmd** [comment]
- 知乎爬虫

  - 实现合理

  - 一些代码可以写得再 pythonic 些，如

    ```python
    i=0
    while i < count:
        dic = {}
        dic['title']=title_list[i]
        dic['heat']=heat_list[i]
        dic['excerpt']=excerpt_list[i]
        dic['url']=url_list[i]
        dic['qid']=num_list[i]
        total_list.append(dic)
        i=i+1
    ```

    可作

    ```python
    total_list = [
        {
            "title": t,
            "heat": h
            "excerpt": e,
            "url": u,
            "qid": n
        } 
        for t, h, e, u, n 
        in zip(title_list, heat_list, excerpt_list, url_list, num_list)
    ]
    ```

- WebVPN

  - 实现鲁棒性可能欠佳，可能涉及了较多因人而异的索引 (?)

    在我的计算机上会出现如下错误

    ```python
    Traceback (most recent call last):
      File "WebVPN_crawler/webvpn.py", line 188, in <module>
        m.get_grades()
      File "WebVPN_crawler/webvpn.py", line 157, in get_grades
        scrs[times.index(ls[i+2])].append(float(ls[i])*float(ls[i-3]))
    ValueError: '必修' is not in list
    ```

  - 似乎没有考虑夏季学期 (?

- SQL
  - 查询正确

- 代码风格

  - 实现之后可以考虑将 `raise NotImplementedError` 和 `TODO `删 去，毕竟您已经实现了功能（当然这是非本质的）

  - 算符前后考虑添加空格，如

    ```python
    if i%10 == 8 and i>12 :
    ```

    可做

    ```python
    if i % 10 == 8 and i > 12:
    ```

##
